[package]
name = "dfx-json-inspector"
version = "0.1.0"
edition = "2021"
authors = ["vishnu"]
license = "MIT/Apache-2.0"
description = "a simple implementation of the dfx-json-inspector"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"